name: Lint Python

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install isort
        pip install flake8
    - name: Analysing the code with black
      run: black --check cli
    - name: Order import with isort
      run: isort cli
    - name: Lint with flake8
      run: flake8 cli
